// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MidProject.Data;

#nullable disable

namespace MidProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723064747_FixPointsStoreMappings")]
    partial class FixPointsStoreMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MidProject.Models.AvatarFrame", b =>
                {
                    b.Property<int>("FrameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrameID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PointsPrice")
                        .HasColumnType("int");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Common");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("FrameID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ImageID");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.ToTable("AvatarFrames", t =>
                        {
                            t.HasCheckConstraint("CK_AvatarFrames_PointsPrice", "[PointsPrice] >= 0");

                            t.HasCheckConstraint("CK_AvatarFrames_Rarity", "[Rarity] IN ('Common', 'Rare', 'Limited')");
                        });
                });

            modelBuilder.Entity("MidProject.Models.BusinessHour", b =>
                {
                    b.Property<int>("BusinessHourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessHourID"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time(0)");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.HasKey("BusinessHourID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("BusinessHours", t =>
                        {
                            t.HasCheckConstraint("CK_BusinessHours_DayOfWeek", "[DayOfWeek] >= 1 AND [DayOfWeek] <= 7");
                        });
                });

            modelBuilder.Entity("MidProject.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("FavoriteFolderID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("FavoriteID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("FavoriteFolderID");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MemberID");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MidProject.Models.FavoriteFolder", b =>
                {
                    b.Property<int>("FavoriteFolderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteFolderID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("FavoriteFolderID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MemberID");

                    b.ToTable("FavoriteFolders");
                });

            modelBuilder.Entity("MidProject.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("UploadedByMemberID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("ImageType");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UploadedByMemberID");

                    b.ToTable("Images", t =>
                        {
                            t.HasCheckConstraint("CK_Images_ImageType", "[ImageType] IN ('RestaurantCover', 'RestaurantEnvironment', 'ReviewImage', 'MemberAvatar', 'AvatarFrame')");
                        });
                });

            modelBuilder.Entity("MidProject.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AvatarImageID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EquippedFrameID")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("NickName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PenaltyEndAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("User");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Normal");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WarningCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MemberID");

                    b.HasIndex("AvatarImageID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EquippedFrameID");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LevelID");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Members", t =>
                        {
                            t.HasCheckConstraint("CK_Members_Experience", "[Experience] >= 0");

                            t.HasCheckConstraint("CK_Members_Points", "[Points] >= 0");

                            t.HasCheckConstraint("CK_Members_Role", "[Role] IN ('User', 'Admin')");

                            t.HasCheckConstraint("CK_Members_Status", "[Status] IN ('Normal', 'Warning', 'Muted', 'Suspended', 'Deleted')");

                            t.HasCheckConstraint("CK_Members_WarningCount", "[WarningCount] >= 0");
                        });
                });

            modelBuilder.Entity("MidProject.Models.MemberAvatarFrame", b =>
                {
                    b.Property<int>("MemberAvatarFrameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberAvatarFrameID"));

                    b.Property<int>("FrameID")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedeemedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MemberAvatarFrameID");

                    b.HasIndex("FrameID");

                    b.HasIndex("MemberID", "FrameID")
                        .IsUnique();

                    b.ToTable("MemberAvatarFrames");
                });

            modelBuilder.Entity("MidProject.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Personal");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SourceReportID")
                        .HasColumnType("int");

                    b.Property<string>("SourceReportOutcome")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("TargetLevelID")
                        .HasColumnType("int");

                    b.Property<string>("TargetRole")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TargetStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NotificationID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("MemberID");

                    b.HasIndex("NotificationType");

                    b.HasIndex("TargetLevelID");

                    b.HasIndex("SourceReportID", "SourceReportOutcome")
                        .IsUnique()
                        .HasFilter("[SourceReportID] IS NOT NULL AND [SourceReportOutcome] IS NOT NULL");

                    b.HasIndex("IsDeleted", "ScheduledAt", "NotificationID");

                    b.HasIndex("IsSent", "IsDeleted", "ScheduledAt", "NotificationID");

                    b.ToTable("Notifications", t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Audience", "([NotificationType] = 'Personal' AND [MemberID] IS NOT NULL AND [TargetRole] IS NULL AND [TargetStatus] IS NULL AND [TargetLevelID] IS NULL) OR ([NotificationType] = 'Condition' AND [MemberID] IS NULL)");

                            t.HasCheckConstraint("CK_Notifications_DeletedState", "([IsDeleted] = 0 AND [DeletedAt] IS NULL AND [DeletedBy] IS NULL) OR ([IsDeleted] = 1 AND [IsSent] = 0 AND [DeletedAt] IS NOT NULL AND [DeletedBy] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Notifications_NotificationType", "[NotificationType] IN ('Personal', 'Condition')");

                            t.HasCheckConstraint("CK_Notifications_ReportSource", "([SourceReportID] IS NULL AND [SourceReportOutcome] IS NULL) OR ([SourceReportID] IS NOT NULL AND [SourceReportOutcome] IN ('Approved', 'Rejected'))");

                            t.HasCheckConstraint("CK_Notifications_SentState", "([IsSent] = 0 AND [SentAt] IS NULL) OR ([IsSent] = 1 AND [SentAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Notifications_TargetRole", "[TargetRole] IS NULL OR [TargetRole] IN ('User', 'Admin')");

                            t.HasCheckConstraint("CK_Notifications_TargetStatus", "[TargetStatus] IS NULL OR [TargetStatus] IN ('Normal', 'Warning', 'Muted', 'Suspended', 'Deleted')");
                        });
                });

            modelBuilder.Entity("MidProject.Models.PointsTransaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RelatedFrameID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TransactionID");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RelatedFrameID");

                    b.HasIndex("Type");

                    b.HasIndex("MemberID", "CreatedAt");

                    b.ToTable("PointsTransactions", t =>
                        {
                            t.HasCheckConstraint("CK_PointsTransactions_BalanceAfter", "[BalanceAfter] >= 0");

                            t.HasCheckConstraint("CK_PointsTransactions_RelatedFrame", "([Type] = 'Redeem' AND [RelatedFrameID] IS NOT NULL) OR ([Type] <> 'Redeem' AND [RelatedFrameID] IS NULL)");

                            t.HasCheckConstraint("CK_PointsTransactions_Type", "[Type] IN ('Redeem', 'AdminAdjust', 'Earn')");
                        });
                });

            modelBuilder.Entity("MidProject.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<string>("AdminNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HandledByMemberID")
                        .HasColumnType("int");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReportedMemberID")
                        .HasColumnType("int");

                    b.Property<int>("ReporterMemberID")
                        .HasColumnType("int");

                    b.Property<int?>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ReportID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("HandledByMemberID");

                    b.HasIndex("ImageID");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ReportedMemberID");

                    b.HasIndex("ReporterMemberID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("ReviewID");

                    b.HasIndex("Status");

                    b.ToTable("Reports", t =>
                        {
                            t.HasCheckConstraint("CK_Reports_Status", "[Status] IN ('Pending', 'Approved', 'Rejected')");
                        });
                });

            modelBuilder.Entity("MidProject.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurantID"));

                    b.Property<decimal>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DeleteReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("DetailedAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("RestaurantID");

                    b.HasIndex("City");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("District");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MemberID");

                    b.ToTable("Restaurants", t =>
                        {
                            t.HasCheckConstraint("CK_Restaurants_AverageRating", "[AverageRating] >= 0 AND [AverageRating] <= 5");

                            t.HasCheckConstraint("CK_Restaurants_Latitude", "[Latitude] IS NULL OR ([Latitude] >= -90 AND [Latitude] <= 90)");

                            t.HasCheckConstraint("CK_Restaurants_Longitude", "[Longitude] IS NULL OR ([Longitude] >= -180 AND [Longitude] <= 180)");

                            t.HasCheckConstraint("CK_Restaurants_ReviewCount", "[ReviewCount] >= 0");
                        });
                });

            modelBuilder.Entity("MidProject.Models.RestaurantImage", b =>
                {
                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.HasKey("RestaurantID", "ImageID");

                    b.HasIndex("ImageID");

                    b.ToTable("RestaurantImages");
                });

            modelBuilder.Entity("MidProject.Models.RestaurantTag", b =>
                {
                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("RestaurantID", "TagID");

                    b.HasIndex("TagID");

                    b.ToTable("RestaurantTags");
                });

            modelBuilder.Entity("MidProject.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MemberID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReportCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReviewID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("MemberID");

                    b.HasIndex("RestaurantID");

                    b.HasIndex("Status");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "[Rating] >= 1 AND [Rating] <= 5");

                            t.HasCheckConstraint("CK_Reviews_ReportCount", "[ReportCount] >= 0");

                            t.HasCheckConstraint("CK_Reviews_Status", "[Status] IN ('Active', 'PendingReview')");
                        });
                });

            modelBuilder.Entity("MidProject.Models.ReviewImage", b =>
                {
                    b.Property<int>("ReviewID")
                        .HasColumnType("int");

                    b.Property<int>("ImageID")
                        .HasColumnType("int");

                    b.HasKey("ReviewID", "ImageID");

                    b.HasIndex("ImageID");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("MidProject.Models.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagID"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TagID");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TagName")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MidProject.Models.UserLevel", b =>
                {
                    b.Property<int>("LevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelID"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MinExp")
                        .HasColumnType("int");

                    b.Property<string>("Rewards")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LevelID");

                    b.HasIndex("LevelName")
                        .IsUnique();

                    b.HasIndex("MinExp")
                        .IsUnique();

                    b.ToTable("UserLevels", t =>
                        {
                            t.HasCheckConstraint("CK_UserLevels_MinExp", "[MinExp] >= 0");
                        });
                });

            modelBuilder.Entity("MidProject.Models.AvatarFrame", b =>
                {
                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Image", "Image")
                        .WithMany("AvatarFrames")
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DeletedByMember");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MidProject.Models.BusinessHour", b =>
                {
                    b.HasOne("MidProject.Models.Restaurant", "Restaurant")
                        .WithMany("BusinessHours")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("MidProject.Models.Favorite", b =>
                {
                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.FavoriteFolder", "FavoriteFolder")
                        .WithMany("Favorites")
                        .HasForeignKey("FavoriteFolderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.Member", "Member")
                        .WithMany("Favorites")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.Restaurant", "Restaurant")
                        .WithMany("Favorites")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DeletedByMember");

                    b.Navigation("FavoriteFolder");

                    b.Navigation("Member");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("MidProject.Models.FavoriteFolder", b =>
                {
                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "Member")
                        .WithMany("FavoriteFolders")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DeletedByMember");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MidProject.Models.Image", b =>
                {
                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "UploadedByMember")
                        .WithMany("UploadedImages")
                        .HasForeignKey("UploadedByMemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DeletedByMember");

                    b.Navigation("UploadedByMember");
                });

            modelBuilder.Entity("MidProject.Models.Member", b =>
                {
                    b.HasOne("MidProject.Models.Image", "AvatarImage")
                        .WithMany()
                        .HasForeignKey("AvatarImageID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.AvatarFrame", "EquippedFrame")
                        .WithMany()
                        .HasForeignKey("EquippedFrameID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.UserLevel", "UserLevel")
                        .WithMany("Members")
                        .HasForeignKey("LevelID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AvatarImage");

                    b.Navigation("DeletedByMember");

                    b.Navigation("EquippedFrame");

                    b.Navigation("UserLevel");
                });

            modelBuilder.Entity("MidProject.Models.MemberAvatarFrame", b =>
                {
                    b.HasOne("MidProject.Models.AvatarFrame", "Frame")
                        .WithMany("MemberAvatarFrames")
                        .HasForeignKey("FrameID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.Member", "Member")
                        .WithMany("MemberAvatarFrames")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Frame");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MidProject.Models.Notification", b =>
                {
                    b.HasOne("MidProject.Models.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Report", "SourceReport")
                        .WithMany("Notifications")
                        .HasForeignKey("SourceReportID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.UserLevel", "TargetLevel")
                        .WithMany("Notifications")
                        .HasForeignKey("TargetLevelID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByMember");

                    b.Navigation("DeletedByMember");

                    b.Navigation("Member");

                    b.Navigation("SourceReport");

                    b.Navigation("TargetLevel");
                });

            modelBuilder.Entity("MidProject.Models.PointsTransaction", b =>
                {
                    b.HasOne("MidProject.Models.Member", "CreatedByMember")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "Member")
                        .WithMany("PointsTransactions")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.AvatarFrame", "RelatedFrame")
                        .WithMany()
                        .HasForeignKey("RelatedFrameID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByMember");

                    b.Navigation("Member");

                    b.Navigation("RelatedFrame");
                });

            modelBuilder.Entity("MidProject.Models.Report", b =>
                {
                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "HandledByMember")
                        .WithMany()
                        .HasForeignKey("HandledByMemberID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "ReportedMember")
                        .WithMany()
                        .HasForeignKey("ReportedMemberID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "ReporterMember")
                        .WithMany()
                        .HasForeignKey("ReporterMemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Review", "Review")
                        .WithMany("Reports")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DeletedByMember");

                    b.Navigation("HandledByMember");

                    b.Navigation("Image");

                    b.Navigation("ReportedMember");

                    b.Navigation("ReporterMember");

                    b.Navigation("Restaurant");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("MidProject.Models.Restaurant", b =>
                {
                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "Member")
                        .WithMany("Restaurants")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DeletedByMember");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MidProject.Models.RestaurantImage", b =>
                {
                    b.HasOne("MidProject.Models.Image", "Image")
                        .WithMany("RestaurantImages")
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.Restaurant", "Restaurant")
                        .WithMany("RestaurantImages")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("MidProject.Models.RestaurantTag", b =>
                {
                    b.HasOne("MidProject.Models.Restaurant", "Restaurant")
                        .WithMany("RestaurantTags")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.Tag", "Tag")
                        .WithMany("RestaurantTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Restaurant");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MidProject.Models.Review", b =>
                {
                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MidProject.Models.Member", "Member")
                        .WithMany("Reviews")
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.Restaurant", "Restaurant")
                        .WithMany("Reviews")
                        .HasForeignKey("RestaurantID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DeletedByMember");

                    b.Navigation("Member");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("MidProject.Models.ReviewImage", b =>
                {
                    b.HasOne("MidProject.Models.Image", "Image")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ImageID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MidProject.Models.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("MidProject.Models.Tag", b =>
                {
                    b.HasOne("MidProject.Models.Member", "DeletedByMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DeletedByMember");
                });

            modelBuilder.Entity("MidProject.Models.AvatarFrame", b =>
                {
                    b.Navigation("MemberAvatarFrames");
                });

            modelBuilder.Entity("MidProject.Models.FavoriteFolder", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("MidProject.Models.Image", b =>
                {
                    b.Navigation("AvatarFrames");

                    b.Navigation("RestaurantImages");

                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("MidProject.Models.Member", b =>
                {
                    b.Navigation("FavoriteFolders");

                    b.Navigation("Favorites");

                    b.Navigation("MemberAvatarFrames");

                    b.Navigation("PointsTransactions");

                    b.Navigation("Restaurants");

                    b.Navigation("Reviews");

                    b.Navigation("UploadedImages");
                });

            modelBuilder.Entity("MidProject.Models.Report", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("MidProject.Models.Restaurant", b =>
                {
                    b.Navigation("BusinessHours");

                    b.Navigation("Favorites");

                    b.Navigation("RestaurantImages");

                    b.Navigation("RestaurantTags");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MidProject.Models.Review", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("MidProject.Models.Tag", b =>
                {
                    b.Navigation("RestaurantTags");
                });

            modelBuilder.Entity("MidProject.Models.UserLevel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
